### ISSUE TITLE
StartListening Thread can take 20-30+ seconds to run

### ISSUE THREAD

**Issue by tdinneen** [microsoft/vs-streamjsonrpc#1011]
We've implemented a wrapper around our JsonRpc calls to have a timeout on them. Issue when things are busy is that it can take 20-30 seconds (sometimes longer looking at TraceEvents) between calling JsonRpc.StartListening and when the listening thread gets to run. So if our first call has a timeout less than the time it takes to start the listening thread then we throw a timeout exception. There doesn't seem to be a way to detect when the receive thread has actually started up. Our workaround for the moment is to have a dedicated call that has a long timeout on it (60 seconds). But that's not very elegant. A better solution would be a Task that we can wait on. Once that task returns we know that the receive thread has started. Could something like that be implemented.

**Comment by AArnott** [comment]
There is no listening _thread_. It's just an async loop that runs on the threadpool. If it takes 20-30 seconds to start, that suggests your process is suffering from threadpool starvation such that the queue takes that long to get to one item on it. Check out [my blog post on throttling work to the thread pool](https://devblogs.microsoft.com/premier-developer/limiting-concurrency-for-faster-and-more-responsive-apps/) to help solve that problem.

While your threadpool is starved, there's nothing we can do. Even if we gave you a Task that completed only after our listening loop _started_, that's no indication at all that it won't take 20-30 seconds to respond to any incoming message because each incoming message triggers an item to be added to the threadpool queue in order to process the message.

Your question seems to suggest that once StartListening's task has started, things run quickly. If that's the case, I can't explain why that would be. Unless _perhaps_ it's because StartListening calls `Task.Run`, which schedules to a threadpool _worker_ thread, while async I/O triggers async methods to resume on a threadpool _I/O completion_ thread. So if it's the _worker_ queue that's bogged down and not the I/O completion queue that's bogged down, I guess that would explain the startup-only delay.

Still though, your process seems highly vulnerable to many perf issues when your threadpool worker queue is moving too slowly. I hope my blog post can offer some ways for you to solve the problem on your side.
