### ISSUE TITLE
Add TFM to enable reduction in explicit dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/vs-streamjsonrpc#1032]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
I want the package to not have a dependencies on packages which can be provided by the framework (net 6/net core 3) ie System.Text.Json

### Describe alternatives you've considered
Accept the additional dependency

**Comment by AArnott** [comment]
@thompson-tomo I see you've filed almost identical issues across several repos. Are you actually impacted by this, or are you just filing issues against repos to achieve a goal you have for all libraries to do this? 
I ask because we want to prioritize customer-filed issues that actually matter to them.

**Comment by thompson-tomo** [comment]
@AArnott yes i have run into issues with conflicting STJ versions due to it being explicitly provided and at the same time for my work project our dependencies are analyzed for vulnerabilities & currentness. The most efficent to achieve that is by leveraging the framework wherever possible. I have already submitted a PR for the change like i have done for a number of the issues i have filled and i will continue submitting PR's if no one does it before i get to it.
