### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by wahmedswl** [Microsoft/vs-streamjsonrpc#14]
Hi,
   It would be great if examples are provided for RPC Server Hosted in IIS + VB/C# client.

Thanks

**Comment by IlyaBiryukov** [comment]
@wahmedswl there are examples in the [JsonRpcTests.cs](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc.Tests/JsonRpcTests.cs).

Generally, the component deals with the streams only. It doesn't know how to create these streams. Establishing the connection and opening the communication stream is out of scope.

Current implementation assumes the stream is durable and more than one message can be sent over it. That's why there is [DelimitedMessageHandler](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc.Shared/DelimitedMessageHandler.cs).
To get the response back, a server->client stream is required, or one bi-directional can be used.

As such we don't have any host-specific examples.

**Comment by knocte** [comment]
@IlyaBiryukov the JsonRpcTests.cs seems too broad.

Ideally, I would expect the first sample in the docs to be the most simple client (not server) that just sends a request and receives a response. This is not easy to figure out from that file.

**Comment by IlyaBiryukov** [comment]
Fair enough.

**Comment by asheeshv** [comment]
@IlyaBiryukov you mentioned 
 >> Generally, the component deals with the streams only. It doesn't know how to create these streams. Establishing the connection and opening the communication stream is out of scope.

Does it mean that the streamJsonRPC doesn't not know how to establish a connection to the other party? In this case, all the plumbing work of establishing connection over TCP/IP, Sockets or HTTP would need to be done in order to use this framework or was it only limited to the test case? It'd be great if you can elaborate. Thanks!

**Comment by AArnott** [comment]
That's correct: the user must set up the stream(s). Once that is set up, you can attach the `JsonRpc` class to the stream(s) and start invoking methods on the remote side. 
The actual transport underneath the Stream can be anything, and is out of scope.

**Comment by Masterkkvn** [comment]
How to setup this library to work over HTTP? Any examples?
