### ISSUE TITLE
Proxy for methods that don't return tasks

### ISSUE THREAD

**Issue by seertenedos** [Microsoft/vs-streamjsonrpc#183]
Currently the proxy only supports interfaces where the methods return tasks. My issue is that in my case i need am trying to add your library between 2 processes over named pipes and the interfaces can't be changed because there is a large amount of code written to use them. Basically i am splitting an application into a few child processes. Since this is an older application everything including interfaces were not done in the async way so nothing returns tasks. Is there a reason why is has to be a return type of task?

**Comment by AArnott** [comment]
As you may already be aware, splitting a process into multiple child processes means preparing each process for new kinds of reliability and performance problems. When your app was a monolithic process, it all went down at once if it crashed, or there was only one thread to become unresponsive due to kernel scheduling or other concerns. But when you're dealing with IPC between processes, you have to be prepared for any subset of processes to crash or become unresponsive. 

For those reasons, synchronous IPC is generally a bad idea. Now I hear what you're saying about legacy requirements. I work on Visual Studio and believe me, we have our share of legacy APIs to honor. But given the recommendation is strongly on the async side, and that JSON-RPC is fundamentally an async protocol, we want StreamJsonRpc to drop you into the "happy path" of doing things right.

In fact, supporting non-Task returning methods would be potentially very problematic because that would mean StreamJsonRpc is responsible to artificially block the calling thread until the result came back. But that can quickly lead to hangs if, for example, the calling thread is your app's UI thread. It can deadlock if the server needs to call back to your client before returning a response, and your client can't respond because its UI thread is hung.

We have ways to address your requirements, and avoid the deadlocks too. We do it at the level of the general requirement of "how do I block the calling thread while executing an async operation?", which is a problem each application must decide how to solve. Our solution is to use the [JoinableTaskFactory](https://aka.ms/vsthreading) as found in the [Microsoft.VisualStudio.Threading](https://www.nuget.org/packages/Microsoft.VisualStudio.threading) library. That can block the UI thread (or any other thread) while executing async operations. In the case of StreamJsonRpc, that means you might have something like this:

```cs
interface IJsonRpcService
{
    Task SomeOperationAsync();
}

// then on the client, you have:
var client = JsonRpc.Attach<IJsonRpcService>(pipe);

// Call the operation, blocking the thread till the operation is done:
joinableTaskFactory.Run(async delegate
{
    await client.SomeOperationAsync();
});
```

The upside of taking this approach is that you're writing new code that is async, which can be called asynchronously in all your *new* scenarios, all the while still satisfying your legacy synchronous requirements. It's a "bridge" into the new async world that can actually work in practice. :)

I hope this works for you.
