### ISSUE TITLE
Suggestion: Named arguments in dynamic proxies

### ISSUE THREAD

**Issue by bddckr** [Microsoft/vs-streamjsonrpc#201]
Currently the created dynamic proxies only allow for positional arguments. I'd love to use the proxies but need named argument objects instead, i.e. `InvokeWithParameterObjectAsync`.

I had a quick skim over the proxy generation and I believe this should be possible, if not please let me know!

**Comment by AArnott** [comment]
Is your requirement based on the client or service side? 

For example, is the server implemented in a way that rejects positional arguments? Or is it that you want to pass in parameter objects when invoking from the client for convenience with the types you're using?

**Comment by bddckr** [comment]
My use case is me wanting to pass parameter objects from the client side. The server I'm talking to is not handling positional arguments sadly.

**Comment by AArnott** [comment]
OK, so you want to pass named arguments from the client because the server requires it. Got it.
IMO it's odd that a server library would require one vs. the other. Unless the server was javascript or some other language that really can't support one of the options, but ironically, it's javascript that can't support _named_ arguments -- positional arguments should be fine for every server. Ah well.

Ya, I wondered if this requirement would come up. Do you have a preference whether to pass in a single parameter object yourself to the client proxy vs. the client proxy methods still take *n* parameters and it will internally arrange them in a parameter object with named arguments and call `InvokeWithParameterObjectAsync`? I'm divided on which to support. If I could support one, I'd do the latter (create the parameter object internally), but I imagine in some protocols like LSP it might actually be more convenient for the client proxy to accept the parameter object directly from the caller.

**Comment by bddckr** [comment]
My preference is the same: Create the parameter object internally and allow the proxy methods take the parameters.

The plan is to have a nice API on the client side so if the proxy method would only take a single object then I'd be forced to do that work of creating one based on a method taking the parameters one by one.

Thanks for being open to the addition/change!

**Comment by AArnott** [comment]
Sounds good. I expect I won't get to this for a few weeks at least, just to set expectations.

**Comment by AArnott** [comment]
Meh, your feature request caught me on a great weekend.  I'm done. :)
