### ISSUE TITLE
It was not possible to find any compatible framework version, The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.

### ISSUE THREAD

**Issue by Chan-Zhang** [Microsoft/vs-streamjsonrpc#240]
When start LUT , the following error shows, what does this error mean?
The output shows as below:

_[23:03:49.062 Error] [TestRunner 1] Testhost process exited with error: It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
Check application dependencies and target a framework version installed at:
C:\Program Files\dotnet\
Installing .NET Core prerequisites might help resolve this problem:
https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The .NET Core framework and SDK can be installed from:
https://aka.ms/dotnet-download
The following versions are installed:
2.1.7 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]_

**Comment by AArnott** [comment]
You know it's funny you brought that up since I *just* hit this myself yesterday. 
I'm using VS 2019 Previews, which now *remove* older .NET Core runtimes and SDKs. So for me, that's what broke it: when the VS installer removed .NET Core 1.x.

You probably are missing .NET Core 1.0 as well. Follow the instructions in the error message to install .NET Core 1.0 and tests will run again.

We run tests for this library on several versions of .NET and .NET Core, which is why if you want to run tests using LUT you need all the runtimes.
