### ISSUE TITLE
Client DynamicProxy cannot receive notification with multiple arguments

### ISSUE THREAD

**Issue by HA07Z7XE** [microsoft/vs-streamjsonrpc#271]
Amongst other request/response patterns, I need to receive the following notification from a server (not mine):
```json
{
  "jsonrpc": "2.0",
  "method": "subscription",
  "params": {
    "channel": "book.BTC-PERPETUAL.raw",
    "data": {
      "timestamp": 1557698623615,
      "prev_change_id": 2360256191,
      "instrument_name": "BTC-PERPETUAL",
      "change_id": 2360256192,
      "bids": [],
      "asks": [
        [
          "change",
          7137.5,
          4700
        ]
      ]
    }
  }
}
```

The relevant documentation on client-only rpc focuses on [dynamicproxy](https://github.com/microsoft/vs-streamjsonrpc/blob/master/doc/dynamicproxy.md). Here is my proxy interface:
```C#
partial interface IDeribitJsonRpcProxy 
{
    event EventHandler<SubscriptionNotificationDto> subscription;
}

public class SubscriptionNotificationDto
{
    public string channel { get; set; }
}
```
#### The error
![image](https://user-images.githubusercontent.com/19978855/57589392-80aa0d00-7512-11e9-83bd-08e5037af3ba.png)

I debugged into the source. The issue seems to be that the `event EventHandler<T>` is mapped to a method which takes 1 argument of type `T`. However, the jsonrpc notification has 2 parameters - `channel` and `data`:
![image](https://user-images.githubusercontent.com/19978855/57589501-cadfbe00-7513-11e9-945c-0581ffb46f0b.png)

Does the library offer a solution I am missing for this? If not, is there quick and dirty hack you can suggest?

I have uploaded a replica of the issue to https://github.com/HA07Z7XE/Deribit.S4KTNET/tree/streamjsonrpc_issue. You just need to run the Sample project and you should be able to replicate.

**Comment by AArnott** [comment]
The dynamic proxy doesn't look like a good fit for it, since the incoming message doesn't conform to a typical .NET event delegate type.
Instead, just pass your method to the AddLocalTargetMethod method on JsonRpc so that it receives the notification.

**Comment by HA07Z7XE** [comment]
Thanks @AArnott . I went with the `JToken` approach in the end,

**Comment by maggo23** [comment]
Dear @AArnott,

I am Marko and I have a question regarding this issue because I have a similar problem...  

The notification example above shows a parameter structure "by-name" (see https://www.jsonrpc.org/specification#parameter_structures). Therefore I would expect that a proxy implementation as follows should work:

```
partial interface IDeribitJsonRpcProxy 
{
    event EventHandler<SubscriptionNotificationDto> subscription;
}

public class SubscriptionNotificationDto
{
    public string channel { get; set; }
    public JObject data { get; set; }
}
```
Maybe a parameter-structure "by-name" is not supported at the moment and you will only accept parameter structure "by-position". What do you think? (I am using version 2.21.10 from nuget.org.)

In my case the notification sent by the server is as follows:
```
{
	"jsonrpc": "2.0",
	"method": "SomethingChanged",
	"params": {
		"value1": "Hello world!",
		"value2": 1234
	}
}
```
And my proxy interface on the client-side looks like:
```
interface IRpcClient
{
	event EventHandler<SomethingChangedEventArgs<string, int>> SomethingChanged;
}

public class SomethingChangedEventArgs<T1, T2> : EventArgs
{
	public T1 value1 { get; set; }
	public T2 value2 { get; set; }
}
```
But on runtime the EventArgs will always be ```null```.  

I would be very grateful for any help. Thank you in advance!
