### ISSUE TITLE
Trows error when result ID is not an Int64

### ISSUE THREAD

**Issue by haakoo** [microsoft/vs-streamjsonrpc#323]
As far as I can tell there is no requirement in either JSON RPC 1.0 or 2.0 that the `ID` needs to be an _int_. The protocol I'm working with also uses strings as `ID`, so any results I get throws an exception in the method `JsonRpc.HandleRpcAsync(JsonRpcMessage rpc)` on line: 

https://github.com/microsoft/vs-streamjsonrpc/blob/d4d8a44a710f5fc728ecb96daba3babe4ce3e3ed/src/StreamJsonRpc/JsonRpc.cs#L1821

**Comment by AArnott** [comment]
This doesn't appear to be a bug. This is as it shows a "result or error" case. This code handles incoming messages, which means we're on the client to receive this error or result message. And since as the client we *determined* the ID to begin with, we therefore know it's a `long` because that's always what we issue. 

We have interop tests to verify that we work properly with string IDs. In fact we recently took [a fix](https://github.com/microsoft/vs-streamjsonrpc/pull/291/files#diff-2eba41192bde2ae51a16aa411035dfb4) so that those servers which improperly respond to our client messages by encoding our number ID as a string still are compatible because we're willing to convert the string back to a long.

**Comment by haakoo** [comment]
So when I have to use strings as the ID this library wont work?

**Comment by AArnott** [comment]
Why would you have to use strings as the ID? If you're using this library on a JSON-RPC server, strings are fine. If you're using this on the client, the library uses numbers for IDs. Either way, it Just Works. 

As a client, this library does not let you control what the IDs are. They are always integers.
