### ISSUE TITLE
StreamJsonRpc.RequestId is not MessagePack formattable by default.

### ISSUE THREAD

**Issue by peterwald** [microsoft/vs-streamjsonrpc#365]
When using StreamJsonRpc with MessagePack, the RequestId object cannot be serialized using the default formatters.

You get an error/stack like this when attempting to do so:

```
System.TypeInitializationException: The type initializer for 'FormatterCache`1' threw an exception. ---> MessagePack.Internal.MessagePackDynamicObjectResolverException: can't find matched constructor. type:StreamJsonRpc.RequestId
   at MessagePack.Internal.ObjectSerializationInfo.CreateOrNull(Type type, Boolean forceStringKey, Boolean contractless, Boolean allowPrivate)
   at MessagePack.Internal.DynamicObjectTypeBuilder.BuildFormatterToDynamicMethod(Type type, Boolean forceStringKey, Boolean contractless, Boolean allowPrivate)
   at MessagePack.Resolvers.DynamicContractlessObjectResolverAllowPrivate.FormatterCache`1..cctor()
```

**Comment by AArnott** [comment]
Ah, sorry. In fact in our own `MessagePackFormatter` in the test project we have a custom formatter as well:

https://github.com/microsoft/vs-streamjsonrpc/blob/93e614acd2ba16113cbb1c909c43c10a48423c57/src/StreamJsonRpc.Tests/MessagePackFormatter.cs#L145-L170

I wonder if simply changing the parameter names of the `RequestId` constructor, or adding an overload, would be enough to satisfy the typeless, contractless resolver that you're using.

**Comment by peterwald** [comment]
Wow, that is earily similar to what I wrote.

I'd prefer not to use the TypelessContractlessResolver, but adding a constructor that takes both the number and string values would probably fix it for this case.

**Comment by AArnott** [comment]
In my investigation so far, adding a constructor is not enough. We'd also need a `DataContractAttribute` on the class and `DataMemberAttribute` on at least one member to satisfy MessagePack. But doing this would result in MessagePack serializing this `RequestId` as an object with a member instead of as a primitive value, so it would actually break the wire protocol.
So you really do need a custom formatter for this type. But what I'm learning too is that there is even more to it, because there's a hidden collection of resolvers that MessagePack uses when serializing members typed as `object` that is much harder to reach in order to inject the custom formatter into.

This and more I'm preparing fixes for ASAP.

**Comment by alanmcgovern** [comment]
@AArnott Not sure if this is helpful or not - but this surfaces when attempting to use NUnit3 and the NUnit3TestAdapater in Visual Studio 16.5 pre1. The Test Explorer refuses to populate now and that exception is in the logs.

**Comment by AArnott** [comment]
Thanks. It's all the same problem and very reproducible. We finished testing the fix and expect to have it available very soon.
