### ISSUE TITLE
CancellationToken isn't supported?

### ISSUE THREAD

**Issue by Pavelyev** [microsoft/vs-streamjsonrpc#435]
Why don't this code throw a CancelledException if timeout gone? I can wait for minutes and then successfully got result and ofc `cts.IsCancellationRequested` will be true.
```
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(1));
var result = await jsonRpc.InvokeWithParameterObjectAsync<int>("Add", new { a = 1, b = 2 }, cts.Token);
```

As I understand if server will not answer for some messages then my program will wait for it until disconnect will happen. And thus resources will lack if it's long running server process

**Comment by AArnott** [comment]
Yes, cancellation is supported. But in .NET cancellation is a cooperative path that involves the operation to acknowledge cancellation. In RPC scenarios this requires the server to acknowledge as well. Otherwise, the client may initiate and cancel thousands of operations all while the server becomes increasingly overwhelmed with work it hasn't actually canceled.

If you wish to disregard the server's acknowledgement and allow your awaiting operations to cancel immediately, you can use [the `WithCancellation` extension method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.threadingtools.withcancellation?view=visualstudiosdk-2019).
