### ISSUE TITLE
Could non-jsonrpc messages from server be omitted without terminating the connection?

### ISSUE THREAD

**Issue by Pavelyev** [microsoft/vs-streamjsonrpc#457]
Sometimes third party server sent events in it's own way (not jsonrpc notifications). It lead to crash and I have to recreate JsonRpc object on native webSocketClient. But meanwhile performing queries falls and new requests have to wait synchronously for recreating JsonRpc.
Can JsonRpc be tuned to just ignore messages that can't be parsed?

**Comment by AArnott** [comment]
The module that would be responsible for that is the `IJsonRpcMessageHandler`, which is a pluggable component. It also sets the policy for how to see message boundaries. If the remote party sends non-JSON-RPC messages, which causes parsing or deserialization errors, to ignore them you'd have to know when to start reading again. How would the handler distinguish the end of the invalid message and the start of the next (maybe valid) one? If the invalid message used the same delimiters within itself that a valid one did, or didn't end with a proper delimiter, we'd have no way to recover and get back on track reading valid messages, even if valid ones followed the invalid one.

This is one reason why I don't think we'd ever support it in the library itself. Your particular server has a significant oddity that whatever workaround you apply, will be specific to your need. For example if you're using the newline delimited message handler and the invalid messages always end in a newline, then recovery is conceivable. But if the invalid message does *not* end in a newline then the next valid message may be lost as well:

```
{ "jsonrpc": "2.0", .... }
some non-JSON-RPC message that doesn't belong{ "jsonrpc": "2.0", ... }
{ "jsonrpc": "2.0", .... }
```

See how we'd drop the second message and only read the first and third? That would be a problem.

So I'm going to Won't Fix this, but with the tip that you can certainly plug in your own `IJsonRpcMessageHandler` that is designed to tolerate the messages you're getting from the server. As long as it can detect message boundaries, it's possible. You could either try to detect whether the message is valid _before_ sending it on to the `IJsonRpcMessageFormatter` to deserialize (e.g. check for `{` as the first character in the message) or you could hand it off but catch deserialization exceptions and just skip that message.
Take a look at the implementations of this interface we already have in the library for ideas. You *might* even be able to derive from a class we offer in order to avoid copying a bunch of code.

My capacity to provide more support to you for this is extremely limited. 

Good luck.

**Comment by Pavelyev** [comment]
I think it's not "wontfix" it's just was a question. Your help is great, Thank you!
