### ISSUE TITLE
`IProgress<T>` order preservation and completion

### ISSUE THREAD

**Issue by n9** [microsoft/vs-streamjsonrpc#473]
I am considering using progress to stream results. I have the following questions that I have not found [in the documention](https://github.com/microsoft/vs-streamjsonrpc/blob/3e24f716b245e5b48ed421134b1c19b7f17ad537/doc/progresssupport.md):
- Is progress synchronous? Or should I expect that `progress.Report()` could be called in parallel?
  - This could cause that a later progress is processed before an earlier. Results will be out of order.
- Will method call end after last `progress.Report()` is processed?
  - I need to wait for all results. Waiting for method call end will not ensure that all results are received.

**Comment by AArnott** [comment]
> Is progress synchronous? Or should I expect that progress.Report() could be called in parallel?

The `IProgress<T>.Report` will *not* be called in parallel. It is called as soon as the `$/progress` message is received and messages are only received sequentially. However something to be cautious of is that `Progress<T>` (the _class_ as implemented by .NET) implements its `Report` method by scheduling invocation of your delegate for later, either on the threadpool or on a `SynchronizationContext` that it captured in its constructor. If on the threadpool, this means ordering guarantees are lost.

> Will method call end after last progress.Report() is processed?

There is no guarantee of that. Although StreamJsonRpc will invoke `IProgress<T>.Report` before the original async RPC call is completed, the `IProgress<T>` implementation such as `Progress<T>` schedules the delegate for 'later' and that 'later' may often come *after* the async method you're awaiting on has completed.

You can use the [`ProgressWithCompletion<T>` class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.progresswithcompletion-1?view=visualstudiosdk-2019) to address your second concern, since that gives you the ability to await on completion of all the progress callbacks as well (after the async RPC method completes). But `ProgressWithCompletion<T>` does not guarantee ordering, so it suffers the same problem as `Progress<T>` in that respect.

So for now, you can get what you want only by using a custom implementation of `IProgress<T>` on the client side.

We actually expect to improve this by offering an `IProgress<T>` implementation that does address the ordering concern in the future, so let's keep this issue active to track this.

**Comment by AArnott** [comment]
BTW @n9, given your goals I wonder if returning an `IAsyncEnumerable<T>`  would be a better fit for you.

**Comment by n9** [comment]
Thank you for you reply. I am aware of `synchronizationContext.Post()` in `System.Progress<T>`. I am using custom implementation of  `IProgress<T>` that processes progress reports synchronously.

The question is whether could I think that future implementation will not fork during processing: A loop will be receiving messages and forking tasks to run user processing.

I was using `IAsyncEnumerable<T>` but streaming is better with push. I could tweak `JsonRpcEnumerableSettings`, but it is global and still the client will send "MoveNext" to server. Moreover, the streaming function could easily return some final stats. When using `IAsyncEnumerable<T>` I would need to have heterogeneous types.

**Comment by n9** [comment]
@AArnott Btw, is it cancellation token supposed to work with `IProgress`? During playing with `IProgress` it seems to me that cancellation is not triggering on 'server' side. (Although wireshark shows that the cancellation message is sent from client.)

**Comment by n9** [comment]
Thank you for the confirmation:
> I do not expect StreamJsonRpc to ever change its behavior of guaranteeing that IProgress<T>.Report is called in order of receiving messages across invocations and relative to the completed result message.

(Finally, I had to return to `IAsyncEnumerable` due to the issue with the `CancellationToken` in the `IProgress`.)

**Comment by AArnott** [comment]
I'm glad you're unblocked.

Re-opening to track the upcoming feature work, as mentioned.

**Comment by AArnott** [comment]
> We actually expect to improve this by offering an `IProgress<T>` implementation that does address the ordering concern in the future, so let's keep this issue active to track this.

I actually just realized that `ProgressWithCompletion<T>` (like `Progress<T>`) captures the `SynchronizationContext` in its constructor. This means that ordering (among the progress updates) *can* be guaranteed by setting a non-concurrent, order preserving SyncContext (e.g. [`NonConcurrentSynchronizationContext`](https://github.com/microsoft/vs-threading/blob/master/src/Microsoft.VisualStudio.Threading/NonConcurrentSynchronizationContext.cs)) before constructing the `ProgressWithCompletion<T>`.
