### ISSUE TITLE
Add full support of jsonrpc v 2.0 named parameters

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vs-streamjsonrpc#48]
Right now we only support parameter objects by locating a server method that accepts one argument of JToken type in [TargetMethod.cs](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/Reflection/TargetMethod.cs)

We should support locating server methods by matching the parameter names to the argument names, e.g. like [here](https://devdiv.visualstudio.com/DevDiv/_git/CascadePrototype/pullrequest/80621?_a=files&path=%2FJsonRpc%2FArguments.cs)

**Comment by AArnott** [comment]
I faintly recall that we had a reason why we couldn't support this, but I don't remember it now. So perhaps it's fine. @tinaschrepfer might remember.

**Comment by efoerster** [comment]
Are the any updates on this? It would be quite useful for implementing the Language Server Protocol.

**Comment by efoerster** [comment]
@AArnott It's not required. But with this limitation the signature of remote method has to be like this
        
        [JsonRpcMethod(Methods.TextDocumentDidOpen)]
        public void OnTextDocumentOpened(JToken arg)
        {
            var parameter = arg.ToObject<DidOpenTextDocumentParams>();
            ...
        }

Or do I miss something? Instead it would be pretty cool if we could avoid the manual conversion and deduce the type via reflection from the declaration in the target class:

        [JsonRpcMethod(Methods.TextDocumentDidOpen)]
        public void OnTextDocumentOpened(DidOpenTextDocumentParams arg)
        {
            ...
        }

**Comment by AArnott** [comment]
@efoerster can you share an example of the JSON-RPC message itself (i.e. the json) that would invoke this method?

If the `JToken` you are receiving is actually a `JObject` that directly deserializes to a `DidOpenTextDocumentParams`, then once we support named arguments, the C# method would not look like what you've proposed, but rather it would take this form:

```cs
[JsonRpcMethod(Methods.TextDocumentDidOpen)]
public void OnTextDocumentOpened(TextDocumentItem TextDocument) {}
```

This is because [per the json-rpc spec](http://www.jsonrpc.org/specification#parameter_structures), when using the params *object*, each field on that object...
> with member names that match the Server expected parameter names. The absence of expected names MAY result in an error being generated. The names MUST match exactly, including case, to the method's expected parameters.

So if the params object today in JSON is actually the serialized version of a `DidOpenTextDocumentParams` object, then that type's *members* (and not the type itself) must be what the method takes as parameters.

Does that raise any concerns for you?
