### ISSUE TITLE
Suggestion: prefix-based server routing

### ISSUE THREAD

**Issue by IlyaBiryukov** [Microsoft/vs-streamjsonrpc#49]
Sometimes multiple json rpc servers have to share the same stream. If we want to support multiplexing of the servers, we should be able to distinguish them. One way to do that is to have a prefix in the method name. On json rpc level, server A with method Foo will have "A.Foo" method, and server B - "B.Foo". 

StreamJsonRpc servers then can add multiple targets and supply prefix for each one for the routing.

**Comment by AArnott** [comment]
This sounds like feature creep from @tinaschrepfer's original requirement of multiple servers listening on one stream, where it was very specifically a fallback scheme and the client was completely unaware that there are multiple servers. 
What is the scenario that would need this? IMO if the client is aware here are multiple servers, why not just open multiple streams?

**Comment by IlyaBiryukov** [comment]
The scenario is when there is only one stream and more streams are expensive to set up and coordinate.
If @tinaschrepfer work can be enhanced to allow fallback servers to specify method name prefix, that would be equivalent to this suggestion.

**Comment by AArnott** [comment]
Why are multiple servers necessary? Why can't one server define all the methods necessary and forward as appropriate?
Alternatively, we could make JsonRpc willing to invoke a *single* method on a single object, passing in the method name and arguments to that method. Then it can dispatch however it likes. We could expose parts of JsonRpc's internals so that it can reuse some of its goodness (like 'best method match' logic). What do you think?

**Comment by IlyaBiryukov** [comment]
When the methods are added dynamically, e.g. in light-up scenarios, the only way to do this now is to add another target object. We cannot add methods to existing object. Having a single method as a proxy will require an ability to pass various arguments to it which we don't have yet.

E.g. on a target object it can be something like this:
```csharp
public async Task Dispatch(string submethodName, JToken? otherArguments);
```

**Comment by AArnott** [comment]
> When the methods are added dynamically

That sounds similar to what the P&T team was asking us to offer as well. At least, they were asking for the ability to hot-swap the target object entirely. Would that help in this case? I'm guessing not if you have multiple paths for light-up scenarios.

> But this sounds more unnatural than supporting prefix routing.

I support not wanting the implementer you're talking about have to re-implement a bunch of functionality JsonRpc offers. We might expose some of those plumbing bits of functionality though so they can be reused. 
IMO prefix routing is a very specialized requirement. I'd rather expose whatever we need to so that you can achieve your requirement but without adding explicit support for features that to the passing observer would seem rather odd, since that adds complexity to the API, docs, etc. that won't be worthwhile to most folks.

A suggestion made on #51 was that folks could wire up each method by its name individually. If that were allowed, even after calls started coming in, that would allow your light-up scenario, I think. If we accepted the general `Delegate` type as the dispatch method rather than require a specific signature, we could even reflect over it to discover parameter types and invoke it so that it's as natural for the customer as any other method. The delegate of course could be defined on any object instance, and they would be invoked by the name you specify when you register it.

Does that sound like it would meet the requirement?

**Comment by IlyaBiryukov** [comment]
Yep, that would also work

**Comment by AArnott** [comment]
I'm working on this.

**Comment by AArnott** [comment]
> When the methods are added dynamically, e.g. in light-up scenarios, the only way to do this now is to add another target object.

Actually I don't think you can do this "now" anyway, since we block adding target objects after listening has started. Opened #62 to track.
