### ISSUE TITLE
Possibility of updating eventarg object when invoked via dynamic proxy?

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#567]
Is it possible to model jsonrpc events "synchronously"? For example, a eventhandler<TEventArg> is called on the server, which updates a property on the TEventArg object and returning the updated TEventArg to the caller? Right now, I'm using Guids/concurrentDictionaries to achieve this.

**Comment by AArnott** [comment]
*Events* in a proxy (which are implemented as `JsonRpc.NotifyAsync` calls) have absolutely no shot at what you're trying to do, because as notifications, the receiver does not even respond.
So putting events aside, if you switched to calling `InvokeAsync` (or simply made an ordinary method on your RPC interface that the dynamic proxy implements) now the receiver gets to send you something back. But in JSON-RPC arguments are *not* sent backward to the caller at the conclusion of the call. So we'll never get to the point where you raise an event with `TEventArg` and the receiver gets to 'mutate' that object in a way that the sender gets to see.

The best you can do with the JSON-RPC protocol then is define a method which both takes and returns a `TEventArg` so that it can return the mutated object. Like this:

```cs
interface IRPCInterface
{
   MyEventArgs ItHappened(MyEventArgs args);
}

class SomeRpcEndpoint : IRPCInterface
{
   public MyEventArgs ItHappened(MyEventArgs args)
   {
      args.Foo++;
      return args;
   }
}

// caller side:

IRpcInterface proxy;
args = proxy.ItHappened(args);
```
