### ISSUE TITLE
Support for multiple jsonrpc client-server pairs over the same websocket?

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#621]
It is possible to share one websocket for two hosts to communicate and act as both the client and the server simultaneously?

E.g., 

1) Host A connects to remote Host B with new JsonRpc(hostAWebSockethandler, hostAServerImplementation).

2) Host B accepts the connection and attaches with JsonRpc.Attach<IHostAServerInterface>(hostBWebSockethandler).

3) Host B creates a new JsonRpc(hostBWebSockethandler, hostBServerImplementation)

4) Host A attaches with JsonRpc.Attach<IHostBServerInterface>(hostAWebSockethandler)

If not, is there a workaround to achieve bidirectional server/client messaging over one websocket? Or should I just open up two websockets?

**Comment by AArnott** [comment]
You cannot set up multiple JSON-RPC connections over one web socket because only one party can be reading from it.
However you don't need to to accomplish your goal: every JsonRpc instance is both client and server.

Just add an RPC target on both ends, and both will be able to act as server. And you already know how to treat a JsonRpc as a client. There's nothing to block you from using it both ways at once.
