### ISSUE TITLE
Memory mapped files support and heap memory allocation

### ISSUE THREAD

**Issue by netcorefan1** [microsoft/vs-streamjsonrpc#629]
Hello,
I would like to ask if it is it possible to use memory mapped files for communication between two local processes. I saw that [Pipelines.Sockets.Unofficial](https://github.com/mgravell/Pipelines.Sockets.Unofficial) provides a [connector](https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/master/src/Pipelines.Sockets.Unofficial/MemoryMappedPipeReader.cs), but I have no idea on how to join the two pieces together. Is this a supported scenario? If so, are there any limitation? I am not sure if the high performance benefits offered by memory mapped files will remain the same if they go through Pipelines.
I have also read that Microsoft uses [Cloudtoid Interprocess](https://github.com/cloudtoid/interprocess) internally and is claimed to be a nearly zero memory heap allocation free. What about vs-streamjsonrpc?
Cloudtoid is designed for memory mapped files, but I prefer vs-streamjsonrpc because I have everything at hand (MessagePack serializer, .NET Events, Strongly-typed requests etc).
Thanks

**Comment by AArnott** [comment]
I don't know much about shared memory between two processes, but it seems to me that RPC based on that would be more complex, and little if any faster. The reason being that given shared memory, the two processes would need to arrange who would write to which block of memory, then have some sort of synchronization whereby one process communicates to the other that it is now safe to read that memory because writing is completed. This seems very similar to what IPC pipes must already be doing behind the scenes, except that IPC pipes is done in the kernel and thus is already super tested and presumably already optimized.

Also, pipes offer some reliability guarantee that one process cannot malfunction and write to unexpected memory locations, leading to possible instability in the other process. With shared memory, a bad process could write and rewrite memory that is shared with the other process such that the other process may suffer in some way.

This library is fundamentally written around the idea of a duplex stream (thus, it's in the name itself). So if you care to author a new Stream (or `IDuplexPipe`) that is implemented in terms of a memory mapped file or shared memory, then you could use this RPC library with it. But we have no plans to implement such a thing here.

**Comment by AArnott** [comment]
> The main reason I wanted to try shared memory is because I noticed a very long slowdown using Named Pipes using the official sample:

@netcorefan1: Of everything that is going on during an RPC call, I'm curious how you determined that named pipes was the cause of the slowdown.

**Comment by netcorefan1** [comment]
@AArnott Regarding the slowdown I edited the other issue in order to avoid any relation with this one. I'll respond you in the other issue.

**Comment by netcorefan1** [comment]
I tried to reproduce the official sample using Mapped file, but without success (I didn't tried the unofficial connector for which the usage is unknown and not something that should be asked here).

The client side:
```
using (var stream = MemoryMappedFile.CreateNew("myMap1", 1024, MemoryMappedFileAccess.ReadWrite).CreateViewStream(0, 1024, MemoryMappedFileAccess.ReadWrite))
{
	//await stream.ConnectAsync();
	await ActAsRpcClientAsync(stream);
}
```
The server side:
```
while (true)
{
	var mmf = MemoryMappedFile.OpenExisting("myMap1");
	var stream = mmf.CreateViewStream(0, 1024);
	var nowait = RespondToRpcRequestsAsync(stream, ++clientId);
}

private static async Task RespondToRpcRequestsAsync(Stream stream, int clientId)
{
	var jsonRpc = JsonRpc.Attach(stream, new Server());
	await jsonRpc.Completion;
}
```
There is no stream.ConnectAsync() and despite all my attempts to synchronize I always end up with connection lost or the client side awaiting forever of the first method call. I didn't tried IDuplexPipe because I wanted to first try something more basilar like the above. After your response I didn't tried further because from what I understand, I will not see any benefit from using shared memory, but mostly troubles (and this seems to be what I have gone when I tried). 

There are situations where I need to quickly exchange simple data. For example returning to the client the result of a method in the form of an enum and then close the communication. I thought that memory mapped files were the best candidate for this kind of job, but from your words seems to be that I was wrong.
