### ISSUE TITLE
Allow setting WebsocketMessageHandler contentSequenceBuilder.MinimumSpanLength in WriteCoreAsync

### ISSUE THREAD

**Issue by highlyunavailable** [microsoft/vs-streamjsonrpc#650]
I'm using vs-streamjsonrpc to send multi-KB JSON documents over the wire to an Unreal game server. Unfortunately, Unreal's implementation of websockets is, to put it politely, abysmal, so the client doesn't properly check the "end of message" flag. The library-provided implementation of WebsocketMessageHandler uses the default span size for the contentSequenceBuilder, which is generally a series of 512-byte arrays, which I then need to reassemble manually on the client side.

I've currently cloned the WebsocketMessageHandler class to make the following one line change:

``` C#
protected override async ValueTask WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken)
{
    Requires.NotNull(content, nameof(content));

    using (var contentSequenceBuilder = new Sequence<byte>())
    {
        contentSequenceBuilder.MinimumSpanLength = this.sizeHint;
```

I notice that the Pipe extension methods (e.g. the `UsePipe` method for Websocket) allow me to set a PipeOptions class that can set the MinimumSpanLength, but while I do want to use Websockets, I also want to increase the MinimumSpanLength so I can throw more data over the wire at once.

I _have_ gotten it working cleanly with a NewLineDelimitedMessageHandler but using a delimited handler and a pipe socket also introduces other problems like having to manually manage my websocket close state and having to manually add a newline to all my json blobs on the client side (since it's Magical Unreal C++, I can't just use NewLineDelimitedMessageHandler on that side).

I'm happy to try an alternate method if you can think of a better way to do this, but I'd prefer not to try to use the socket as a pipe and then use the other message handlers (e.g. delimited), especially since this seems to be more of a buffer size issue than truly a websocket issue (I say that because I can set the size on pipes, but not websockets).

I can contribute the code myself, I'm just not sure of A. what the perf implications are for doing this (if anything, it'd probably be an increase due to bigger buffers being sent if the data is otherwise large) and B. where this kind of change should go on the websocket message handler constructors.

**Comment by AArnott** [comment]
Thanks for thinking through this and offering ideas. Just so I'm clear on the scenario, can you confirm my understanding that StreamJsonRpc is running within your unity game and connecting to another JSON-RPC implementation that you can't control?

It sounds like the Unreal game engine *does* read in an entire web socket "packet" at once, such that if an *entire* JSON-RPC message is sent with a single `WebSocket.SendAsync` call that the Unreal engine can process it, but not if the message is broken up across several packets. Is that right?

Further, your idea is that if you just make the "MinimumSpanLength" as large as your largest conceivable message, then you'll never have a message split across multiple SendAsync calls, and therefore it shows up as one websocket packet and Unreal will be able to receive it. Correct?

If so, I see two potential weaknesses with the strategy:
1. You may underestimate your largest message size causing failures, or overestimate causing memory overallocation.
2. A single large write to a web socket may actually be implemented as split across multiple packets anyway, as an implementation detail (or protocol requirement?) of the `WebSocket` class itself, leading to Unreal again failing.

I'm not sure I can recommend a better way (other than file a bug against Unreal). And I'm not keen on adding sketchy workarounds to the library that may not work reliably or lead people to over-allocate memory. 

So I guess my recommendation is fork the handler to do whatever works for you. You don't have to fork the entire library, since the handler is an extensibility point.

**Comment by highlyunavailable** [comment]
Yeah fair. I just used the NewlineDelimited handler instead and did my own websocket handling, and I fed the handler a duplex pipe that I created out of the websocket, so it works. I figured out point 1 after I filed this bug as well, so... yeah, my bad. Delimited = good in this case. Thanks for the response!
