### ISSUE TITLE
Add option to cancel outbound requests without waiting for server acknowledgement

### ISSUE THREAD

**Issue by pandaGaume** [microsoft/vs-streamjsonrpc#678]
When not responding server (connected but faulted), and when the client want to cancel (timeout) using CancellationToken, the client is block for ever waiting for a response.
this happend [here](https://github.com/microsoft/vs-streamjsonrpc/blob/4ce94133e98339c1651b6318b4837d0df165dc12/src/StreamJsonRpc/JsonRpc.cs#L1743)

```
 // Arrange for sending a cancellation message if canceled while we're waiting for a response.
 try
 {
       using (cancellationToken.Register(this.cancelPendingOutboundRequestAction, request.RequestId, useSynchronizationContext: false))
        {
            // This task will be completed when the Response object comes back from the other end of the pipe
            return await tcs.Task.ConfigureAwait(false);
        }
  }
  finally
  {
      if (cancellationToken.IsCancellationRequested)
      {
          this.CancellationStrategy?.OutboundRequestEnded(request.RequestId);
      }
  }
```
We might break the wait when the token is cancelled. Using the following code make the trick.

```
   // Arrange for sending a cancellation message if canceled while we're waiting for a response.
    try
    {
        Action<object> d = (o) =>
        {
            this.cancelPendingOutboundRequestAction?.Invoke(o);
            tcs.TrySetCanceled();
        };
        using (cancellationToken.Register(d, request.RequestId, useSynchronizationContext: false))
        {
            // This task will be completed when the Response object comes back from the other end of the pipe
            return await tcs.Task.ConfigureAwait(false);
        }
    }
    finally
    {
        if (cancellationToken.IsCancellationRequested)
        {
            this.CancellationStrategy?.OutboundRequestEnded(request.RequestId);
        }
    }
```
However, this approach may break some cancellation Strategy which may also waiting for a response from the server.
Let me know if you have an idea on the topic.

Many thanks for this lib. Amazing work.
G.

**Comment by AArnott** [comment]
It is by design that the Task we return from `InvokeAsync` only completes when we get a response from the server. Doing otherwise may allow onbounded concurrency on the server if the client breaks out early after "cancelling" and then repeats a similar command, cancels that, repeats, all while the server does not honor cancellation. 
Not completing the task before the server acknowledges the cancellation also emulates .NET behavior where you pass a CancellationToken to a method and then cancel the tokes: you are still at the mercy of that method to recognize the token's cancellation and throw before the client may resume.

Where you know the server may be sluggish or unresponsive and want to break out forcefully, the same technique works whether RPC is involved or not: apply the [`WithCancellation`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.threadingtools.withcancellation?view=visualstudiosdk-2019) or [`WithTimeout`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.threading.tplextensions.withtimeout?view=visualstudiosdk-2019) extension methods on `Task`. This may look like this:

```cs
await client.SomeMethodThatMayHangAsync(
   cancellationToken) // always notify the server/receiver that we want to cancel
   .WithCancellation(cancellationToken); // also abort awaiting on the client immediately
```

**Comment by AArnott** [comment]
Also: if the server has faulted, if it can be fixed to disconnect when faulted, that will immediately lead to the client `JsonRpc` completing all pending outbound requests with an exception. A server that faults in an unresponsive way but leaves the connection open is... not great.

**Comment by pandaGaume** [comment]
@AArnott  Andrew thank for taking the time to anwser. There is few "not great" behaviour on IOT world. For sample, if you deal with a TCP connection backing by a gsm/lte network, it often leave the connection open, as there is something at the remote end, when the device is off network. The device is not faulted and the device's server healthy, and the tcp connection is still there, backed by a ghost proxy somewhere in the operator network, it's like sending your packet in a black hole. 
I will investigate  `WithCancellation.` as you sugest.
Many thanks.

**Comment by AArnott** [comment]
Thanks for the added context. If the extension method approach I prescribed is too tedious to apply everywhere, we might consider adding an option to `JsonRpc` to allow breaking out immediately on cancellation that you could set at the client-side.

**Comment by AArnott** [comment]
I've reactivated to track adding the option.
As for whether your code sample in the description is the best way, I won't know that till we actually look into delivering on this feature request. I can't promise a timeline for that either at this point.
