### ISSUE TITLE
Byte order mark at start of UTF-8 JSON message can throw off interop with other JSON-RPC libraries

### ISSUE THREAD

**Issue by NaolShow** [microsoft/vs-streamjsonrpc#695]
Hi! I am trying to make the library work with a go rpc server. But for whatever reason the rpc message always have some unicode chars that just completely mess with json, and so the go server cannot deserialize json and then I have an error.

Here's my code:
```cs
// Initialize a tcp client
TcpClient client = new();
client.Connect("127.0.0.1", 7777);

// Get the network stream
NetworkStream stream = client.GetStream();

// Here I'm absolutely not sure, never played with streams and for some reason the NewLineDelimitedMessageHandler do not accept raw stream.
PipeReader reader = PipeReader.Create(stream);
PipeWriter writer = PipeWriter.Create(stream);
DuplexPipe pipe = new DuplexPipe(reader, writer);

JsonMessageFormatter formatter = new(System.Text.Encoding.UTF8);
IJsonRpcMessageHandler handler = new NewLineDelimitedMessageHandler(pipe, formatter);

JsonRpc rpc = new JsonRpc(handler);
rpc.StartListening();

bool result = await rpc.InvokeWithParameterObjectAsync<bool>("MyTarget", new { param = "hey" });

// Message received by the go server:
// json-rpc2: invalid character '├»' looking for beginning of value, for input "\ufeff{\"jsonrpc\":\"2.0\",\"id\":2,\"method\":\"MyTarget\",\"params\":{\"param\":\"hey\"}}"
// See the \ufeff char
```

If you know the service, the go rpc server is from Itch.io (indie game hosting) => https://github.com/itchio/butler/tree/master/butlerd
But I don't think the problem comes from their side (?)

Thanks.

**Comment by AArnott** [comment]
I suspect your problem is here:
```cs
JsonMessageFormatter formatter = new(System.Text.Encoding.UTF8);
```

You are explicitly setting the encoding to UTF8, which defaults to emitting a byte-order mark. It sounds like those might be those problematic bytes you were seeing.

Our default is UTF8 *without* a byte-order mark:

https://github.com/microsoft/vs-streamjsonrpc/blob/c393c314b5e5779a9960a7b8e0ba6059ba04bb41/src/StreamJsonRpc/JsonMessageFormatter.cs#L59

You can either copy this syntax to remove the BOM, or simply stop setting it explicitly and inherit the default that you want.

**Comment by NaolShow** [comment]
After trying this yes that was the problem!

Thank you so much, was struggling for about an hour now..

I close the issue, thanks again!
