### ISSUE TITLE
Dynamic proxies and non-public methods?

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#719]
Just confirming that, AllowNonPublicInvocation=false covers everything (e.g., internal, protected, etc.) except for 'public' and also wanted to know if the generated proxies expose public methods not defined in the interface? E.g.,
```c#
public interface IClient
{
    public Task DoStuffPublicAndDefinedInInterface();
}


public class ClientImplementation : IClient
{
    public Task DoStuffPublicAndDefinedInInterface()
    {
    }

    public Task DoStuffPublicNotDefinedInInterface()
    {
    }

    internal Task DoStuffInternal()
    {
    }

    protected Task DoStuffProtected()
    {
    }

    private Task DoStuffPrivate()
    {
    }
}
```
Would everything except for `DoStuffPublicAndDefinedInInterface` be invokable by the client using a proxy generated for `IClient`? What about if AllowNonPublicInvocation were set to true by the server?

**Comment by AArnott** [comment]
Public methods on an RPC target object bare always accessible by the client.
AllowNonPublicInvocation=false *adds* all the other members too.

A dynamic proxy on the client side can only invoke members defined on the interface as it is defined on the client, because after all the only thing the client can see is the interface. There simply is no way to invoke anything else given that interface. That doesn't mean that the server will be willing to invoke all those members or defines all those members, or that the server doesn't offer more than what's on the interface.
The server needn't even implement the interface. Since it's over RPC, CLR type rules like that don't apply.
