### ISSUE TITLE
Add support for Timeouts

### ISSUE THREAD

**Issue by AdamoT** [microsoft/vs-streamjsonrpc#727]
It seems the library doesn't support timeouts at the moment which is very cumbersome if there are communication issues or errors on the other side.
Assume there is a client that invokes rpc expecting a response:
`var response = await rpc.InvokeAsync<string>("Echo", "Hello World");`
If the server is connected but doesn't process the request properly, this call will never end blocking further instructions on the client.
Even if the above is changed to use cancellationToken:
```
var cancellation = new CancellationTokenSource(5000);
var response = await rpc.InvokeWithCancellationAsync<string>("Echo", new[] { "Hello World" }, cancellation.Token);
```
The request is cancelled after 5s but the Task would still never end (this is documented behaviour but doesn't fix the described issue).

An easy solution would be to add e.g. a ReceiveTimeOut at JsonRpc class level, periodically check all pending requests and set TimeOutException on all timeouted requests.

Btw. it is really great library, welly well structured and written! :)

**Comment by lostmsu** [comment]
While `WithCancellation` generally works it gets tedious do add it instead of using the regular `CancellationToken` parameter. It is also unclear how to gracefully terminate the whole RPC setup when remote party stops responding while using `WithCancellation`

**Comment by AArnott** [comment]
`WithCancellation` is _not_ equivalent to passing in a cancellation token, just to be clear. 

The `WithCancellation` extension method, which is orthogonal to StreamJsonRpc by the way, does _not_ cancel the request. It merely stops the client from waiting any more and throws OCE in order to break out of the await for the response. It's a break-glass type thing when you need to ensure you stop waiting for a response without waiting for the server to acknowledge the cancellation. And in such cases, it's usually a good idea to also pass the cancellation token in the original request as well so that at least the server can be notified that the client isn't interested in the response any more rather than toil on without knowing.
