### ISSUE TITLE
Discriminate dynamic proxy generated methods by argument type?

### ISSUE THREAD

**Issue by vflame** [microsoft/vs-streamjsonrpc#738]
Is it possible to discriminate between methods generated by dynamic proxies based on argument type? If not, then can this type of collision be detected and an exception thrown when the proxy is being generated?

For example:
```c#
public interface MyInvokables
{
    public Task Process(Foo data);
    public Task Process(Bar data);
    public Task Process(Baz baz);
}
```
Invoking the above using dynamic proxies always calls the first method that appears in the interface, in this case, `Process(Foo data);`

For dynamic proxies, the documentation says that
`They always pass arguments using positional arguments rather than named arguments.` 
but I think that is no longer the case with https://github.com/microsoft/vs-streamjsonrpc/issues/201

**Comment by AArnott** [comment]
Good call on the outdated documentation. I've fixed it.

Regarding your discrimination question, it actually has nothing to do with the client at all, proxy or otherwise. The problem is on the server side, where all it has is a method name and an untyped argument. StreamJsonRpc resolves overloads by trying to deserialize the arguments into each method signature's parameters, starting with parameter count matching argument count and moving onto deserialization. Any failed deserialization attempt knocks that overload out of the contest. 
When there is more than one compatible signature, the overload chosen is ... either undefined or 'the first one' that you observed. I can't remember if we make any guarantees about that.

So in general, RPC servers should _not_ use method overloads where such ambiguity exists. The easiest way to avoid this is use unique method names or that the required/optional parameter count is such that a simple count of arguments would resolve it. The deserialization test is not only hard to predict whether one type might "fit" into another, but it's incredibly inefficient to deserialize the same argument multiple times just to see what works.

**Comment by vflame** [comment]
The explanation makes sense--would be good to explicitly call out this behavior in the documentation since it differs from your typical c# method overloading and highlight unique names as a good practice. Thanks!

**Comment by AArnott** [comment]
Oh, I suppose another disambiguator is (or should be!) the argument names in the case of named arguments. I'll make sure the library does that, then document this best practice. We can keep this issue open to track this.
