### ISSUE TITLE
Refactor DelimitedMessageHandler so it is Stream-agnostic

### ISSUE THREAD

**Issue by AArnott** [Microsoft/vs-streamjsonrpc#80]
We have at least one user that wants to use this library over a WebSocket, which is not exposed as a Stream. StreamJsonRpc can work with this by deriving from `DelimitedMessageHandler`, but it requires faking out the `DelimitedMessageHandler` with `Stream.Null` instances in order to indirectly control the return values of the `CanRead` and `CanWrite` properties.

When we have a chance for some minor binary breaking changes, we may want to refactor this class so that implementations that aren't dependent on Stream will work.

**Comment by cwillisf** [comment]
I'm trying to do just this: I have a `WebSocket` and I'd like to use `StreamJsonRpc` to do JSON-RPC 2.0 bidirectionally over the socket. Could you provide more detail about what you mean by "it requires faking out the `DelimitedMessageHandler` with `Stream.Null` instances in order to indirectly control the return values of the `CanRead` and `CanWrite` properties"?

I've created a new class which derives from `DelimitedMessageHandler`, and the constructor provides `Stream.Null`s and `Encoding.UTF8` to the base ctor. My class then runs a loop which calls `var receiveResult = await _webSocket.ReceiveAsync(...)` and generates message strings from that. I figured the next step was to put those into a queue that `ReadCoreAsync` will pull from, and then set `CanRead` based on whether or not the queue is empty. However, I'm having trouble figuring out how to "indirectly" control the return value of `CanRead`. Am I on the right track? If so, can I have a hint about the next step(s)?

Also, I've only just started thinking about `WriteCoreAsync` but I don't immediately see what role `CanWrite` will play in that. It seems like I could just kick off a write to the WebSocket inside of `WriteCoreAsync` but I imagine that would violate... something. Any help would be appreciated!

Thanks!

**Comment by AArnott** [comment]
@cwillisf  Can you use the [StreamJsonRpc 1.4 beta](https://www.nuget.org/packages/StreamJsonRpc/1.4.46-beta)? That has `WebSocketMessageHandler` built-in. Note if you're writing software that runs in the devenv.exe process, you should use the version of `StreamJsonRpc` that ships with VS. But if you don't run in that process (either in another app or perhaps as an out of proc extension) then you can use 1.4 beta.

But if you're restricted to StreamJsonRpc 1.3, then you _might_ be able to get away with simply copying the source for [this class](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/src/StreamJsonRpc/WebSocketMessageHandler.cs) into your extension and using it with 1.3.

**Comment by MikhailNatalenko** [comment]
OH MY GOD! I spent so many time to make it work! (i'm newby in dotnet). I think, you should add example for dummies like me

"""
static ClientWebSocket ws = new ClientWebSocket();
static WebSocketMessageHandler wrapper = new WebSocketMessageHandler(ws);
static JsonRpc jsonRpcnew = new  JsonRpc(wrapper); 
"""

**Comment by AArnott** [comment]
@MikhailNatalenko Sorry for your bad experience. We *do* have [documentation](https://github.com/Microsoft/vs-streamjsonrpc/blob/master/doc/index.md), including a server-side sample of using web sockets.

https://github.com/AArnott/StreamJsonRpc.Sample/blob/c9990f09695d07273ac08aebb7b66b8762e22234/StreamJsonRpc.Sample.Web/Controllers/HomeController.cs#L21-L23

Did you know about that?
