### ISSUE TITLE
Additional Exception Logging for Header Delaminated Message Handler

### ISSUE THREAD

**Issue by AustinBurke-Synergex** [microsoft/vs-streamjsonrpc#810]
Sometimes the JsonRpc servers Synergex is connecting to will unintentionally break protocol. We would like to get better debugging diagnostics when this occurs. When bugs in the remote server cause a protocol break we are seeing a JsonRpcConnectionLost Exception which doesn't provide enough information to track down the bug in the server. It looks like the protocol break is detected [here](https://github.com/microsoft/vs-streamjsonrpc/blob/9017a5cade637dbac8eaa4bb4400045179f3a675/src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs#L475), It looks like if we add the received contents of the stream here, we should be able to access them [here](https://github.com/microsoft/vs-streamjsonrpc/blob/6dc57e800961bf40bca23b87c5cf194f9e7c99d7/src/StreamJsonRpc/JsonRpc.cs#L238)

**Comment by AArnott** [comment]
One challenge would be how much of the content of the stream do you include in the exception. When a parsing failure occurs, you no longer have a clear idea of where a message boundary is, or in this case even the header boundary. You _could_ just include a snippet of whatever buffer you were parsing at the time, although that might include data from the surrounding messages.

Without any changes to the library, you could create a Steam-derived class that logs all bytes going across to a rolling buffer, and when the exception is thrown, store the content of that buffer someplace you can investigate later. 
You might also be able to glean more info via a TraceSource listener that listens to verbose events (though I'm not sure that would help with a parsing error, since most trace events are emitted after parsing a message).

In general, it's considered good security practice to _not_ include user data in exceptions because they could get logged or even returned to a remote party, providing an information disclosure vulnerability. Given the risk of user data being included in the buffer, I don't think we'd make a change in the library to include more info in the exception.

**Comment by AustinBurke-Synergex** [comment]
The suggestion to use a stream derived class to log the bytes worked to resolve the issue. Thank you for the suggestion and the insight into the security risk.
