### ISSUE TITLE
Seekable stream support

### ISSUE THREAD

**Issue by hakito** [microsoft/vs-streamjsonrpc#820]
I am using a JsonRpc server based on a MultiplexingStream to allow stream based communication.

I use File.Open on the server to return a stream to the client. The client uses the ZipArchive class to write to the stream (with ZipArchiveMode.Update).

But the call for the ZipArchive constructor fails because the Stream returned to the client is not seekable.

Is it possible to get a seekable stream or add support for it?

**Comment by AArnott** [comment]
I'm afraid that would require an entirely new protocol and would be _much_ slower, since every single stream operation would turn into an RPC call. Our current stream support is analogous to a NetworkStream, which is not seekable. It acts like a pipe, where everything written is immediately sent to the other end, and every read simply waits for data to come over. 
That's out of scope for this library.

One workaround would be to copy the content of the stream into a MemoryStream until you reach the end of the file. Then you have a seekable copy.
