### ISSUE TITLE
Split packages to eliminate unused dependencies

### ISSUE THREAD

**Issue by ishanpranav** [microsoft/vs-streamjsonrpc#829]
I recently worked with the robust StreamJsonRpc library and was very happy with the results. I chose MessagePack serialization since its compactness lends itself well to network streaming. Even though I don\'t use the JSON features, StreamJsonRpc still (potentially unnecessarily?) depends on `Newtonsoft.Json`. In fact,  even though most use cases presumably only use MessagePack _or_ JSON serialization, the existing project structure forces all clients to install _both_ third-party serialization packages.

Following naming conventions established by earlier Microsoft projects, it would be nice to see a new project structure that looks something like this:
| Package | Dependencies | Description |
| --- | --- | --- |
| **`StreamJsonRpc`** | `StreamJsonRpc.Core`, `StreamJsonRpc.NewtonsoftJson`, `StreamJsonRpc.MessagePack` | Maintains the existing package for compatibility. Composite package that includes the default built-in message formatters. |
| **`StreamJsonRpc.Core`** | (None) | Contains the core JSON-RPC library with abstract extension points. |
| **`StreamJsonRpc.MessagePack`** | `StreamJsonRpc.Core`, `MessagePack` | Adds the MessagePack-CSharp message formatter. |
| **`StreamJsonRpc.NewtonsoftJson`** | `StreamJsonRpc.Core`, `Newtonsoft.Json` | Adds the Newtonsoft.Json message formatter. |

Based on my (somewhat superficial) review of the code, this seems feasible and benefitial for the long term. Clients would only need to install the message formatters that they need.

The extra modularity would make the project more extensible. Although this team has already decided against migrating to System.Text.Json, third parties could do so without keeping redundant dependencies. This makes creating a stand-in replacement for Newtonsoft.Json much more viable.

Thank you for your consideration!

**Comment by AArnott** [comment]
It's a fine idea, and thank you for describing it so well. 

It's not as simple as that, unfortunately. The biggest problem is backward compatibility. Removing types from StreamJsonRpc.dll would be a breaking change unless we used `TypeForwardedToAttribute`, which requires that StreamJsonRpc.dll reference the assembly the type was moved to, which defeats the point of dropping the dependency.

Also, we actually use Newtonsoft.Json.dll internally for a few things including logging, capturing the content of a message as JSON in an exception, and perhaps a few other things. Dropping the MessagePack dependency might work because at its core I don't think StreamJsonRpc uses it for anything outside the formatter. But again, we'd have the backward compatibility problem. 

Backward compatibility is a huge priority for this library, so I'm afraid we can't refactor it at this point. Future formatters we add (if any) could likely be factored in the way you propose though, where it's an extra nuget package that adds the formatter. We can't make guarantees about unknown future features though.
