### ISSUE TITLE
Getting  vs-streamjsonrpc working with AirSim (MessagePack)

### ISSUE THREAD

**Issue by tank104** [microsoft/vs-streamjsonrpc#870]
Hi,
Firstly nice work on this library- looks like great packages!

I am trying to get this working with AirSim - that uses MessagePack RPC
This code in Python works:
```
client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout = timeout_value, pack_encoding = 'utf-8', unpack_encoding = 'utf-8')
return self.client.call('isApiControlEnabled', vehicle_name)
```
It sends a TCP message like:
94 00 00 B3 69 73 41 70 69 43 6F 6E 74 72 6F 6C 45 6E 61 62 6C 65 64 91 A0
Which unpacks to (using this https://kawanet.github.io/msgpack-lite/):
[
0,
0,
"isApiControlEnabled",
[
""
]
]

I have tried lots of different code, but this is current iteration:
```
        TcpClient tcpClient = new TcpClient("127.0.0.1", 41451);
        Stream jsonRpcStream = tcpClient.GetStream();
        var clientFormatter = new MessagePackFormatter();
        var clientHandler = new LengthHeaderMessageHandler(jsonRpcStream, jsonRpcStream, clientFormatter);
        using (var jsonRpc = new JsonRpc(clientHandler)) //, new WebSocketMessageHandler(socket)))
        {
          jsonRpc.StartListening();
          var isApiControlEnabled1 = await jsonRpc.InvokeAsync<bool>("isApiControlEnabled", new object[] { 0, msgCounter++, "isApiControlEnabled", new string[] { "" } });
        }
```
It sends TCP Message like this (from wireshark):
0000   02 00 00 00 45 00 00 80 d5 1e 40 00 80 06 00 00   ....E.....@.....
0010   7f 00 00 01 7f 00 00 01 cf 7b a1 eb 4a 8f dd 5d   .........{..J..]
0020   6f 88 cd 24 50 18 04 ff 84 5c 00 00 00 00 00 54   o..$P....\.....T
0030   84 a7 6a 73 6f 6e 72 70 63 a3 32 2e 30 a2 69 64   ..jsonrpc.2.0.id
0040   02 a6 6d 65 74 68 6f 64 b3 69 73 41 70 69 43 6f   ..method.isApiCo
0050   6e 74 72 6f 6c 45 6e 61 62 6c 65 64 a6 70 61 72   ntrolEnabled.par
0060   61 6d 73 94 d2 00 00 00 00 d2 00 00 00 00 b3 69   ams............i
0070   73 41 70 69 43 6f 6e 74 72 6f 6c 45 6e 61 62 6c   sApiControlEnabl
0080   65 64 91 a0                                       ed..

But the body is this:
00 00 00 55 84 a7 6a 73 6f 6e 72 70 63 a3 32 2e 30 a2 69 64 02 a6 6d 65 74 68 6f 64 b3 49 73 41 70 69 43 6f 6e 74 72 6f 6c 45 6e 61 62 6c 65 64 a6 70 61 72 61 6d 73 91 94 d2 00 00 00 00 d2 00 00 00 00 b3 69 73 41 70 69 43 6f 6e 74 72 6f 6c 45 6e 61 62 6c 65 64 91 a0

Interesting the last part is right -  94 d2 00 00 00 00 d2 00 00 00 00 b3 69 73 41 70 69 43 6f 6e 74 72 6f 6c 45 6e 61 62 6c 65 64 91 a0
But it adds a lot of info before it that is breaking it.

How do I get this workign properly?  What am I doing wrong?

**Comment by AArnott** [comment]
I'm not familiar with AirSim or "MessagePack RPC". The decoded msgpack you shared isn't JSON-RPC encoded as messagepack either. If this is some other RPC protocol, I wonder whether StreamJsonRpc is even a good fit here. You may want to find a .NET RPC library that actually speaks the same protocol as AirSim. 

StreamJsonRpc does offer a MessagePackFormatter, which encodes a JSON-RPC message with messagepack instead of as UTF8 JSON. And theoretically you could write a custom handler and formatter for StreamJsonRpc that could presumably get it to talk to just about any RPC system so long as you could transform each message to and from JSON-RPC messages. But unless the remote party is speaking JSON-RPC in some way or other, I suspect you'd be better off finding or writing a library intended for whatever that protocol is.

**Comment by tank104** [comment]
@AArnott thanks so much for taking the time to reply - and appreciate the response.

I was worried I was completely misunderstanding something and it turns out I was quite wrong in this case.
