### ISSUE TITLE
JsonRpc over HTTP fails

### ISSUE THREAD

**Issue by 4gsim** [microsoft/vs-streamjsonrpc#917]
I am trying to do JsonRpc over HTTP with HeaderDelimitedMessageHandler but i get the error:
**Reading JSON RPC from the stream failed with BadRpcHeaderException: Colon not found in header.**

The curl command is:
curl -X POST -d '{"jsonrpc":"2.0","id":1,"method":"test"}' http://localhost:22080 -v

**Comment by AArnott** [comment]
What you're trying to do is not supported.

JSON-RPC is a P2P protocol, whereas HTTP is a request-response protocol. If you really want to do it though, you have a couple options:
1. Establish a web socket over HTTP and use `WebSocketMessageHandler` instead of `HeaderDelimitedMessageHandler`. This allows full functionality of the library.
3. Create your own message handler that uses `HttpClient` as a transport. This will _not_ have full JSON-RPC functionality because of the strict request-response paradigm. You may find that [`HttpClientMessageHandler`](https://github.com/microsoft/vs-streamjsonrpc/blob/main/test/StreamJsonRpc.Tests/Samples/HttpClientMessageHandler.cs) is a good starting point for your code.
