### ISSUE TITLE
Connection with Java-based JSON-RPC server fails because Content-Length is required

### ISSUE THREAD

**Issue by georghinkel** [microsoft/vs-streamjsonrpc#979]
I am trying to connect to a Java server running a JSON-RPC server on a websocket. However, when I try to connect, the Java server fails with an `java.lang.IllegalStateException: Missing header Content-Length in input "GET / HTTP/1.1`. This seems to hit exactly [this issue](https://github.com/eclipse-lsp4j/lsp4j/issues/210) on the Java side, but I am struggling to make it work in the first place, i.e. to equip the calls sent to the server with the appropriate headers.

My code is the following:

```csharp
using (var socket = new ClientWebSocket())
{
    // socket.Options.SetRequestHeader("Content-Length", "0"); <-- I tried this, but did not help
    using (var rpc = new JsonRpc(new WebSocketMessageHandler(socket)))
    {
        var server = rpc.Attach<IGlspServer>();
        rpc.StartListening();
        var initializeParameters = ...
        await socket.ConnectAsync(new Uri("ws://localhost:5007/"), cancellationToken);
        var initializationResult = await server.InitializeAsync(initializeParameters);
        Console.WriteLine(initializationResult.ProtocolVersion);
    }
}
```

The error on the Java server is the following:

```
java.lang.IllegalStateException: Missing header Content-Length in input "GET / HTTP/1.1
Host: localhost:5007
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Key: rhZWNoXSckaw+p1VfCOpqQ==
Sec-WebSocket-Version: 13
```

The code is adapted from the [StreamJsonRpc samples](https://github.com/AArnott/StreamJsonRpc.Sample/blob/master/StreamJsonRpc.Sample.WebSocketClient/Program.cs), but it seems like calling `ConnectAsync` is not intercepted by StreamJsonRpc, but I don't see how I would establish the Websocket connection otherwise. What am I doing wrong?

**Comment by AArnott** [comment]
Shouldn't you connect the web socket before hooking RPC to it? That's how the samples you linked to do it. I'm not sure that that's causing your problem, but that's the first thing I would do to your code.

If the JSON-RPC implementation you're running on the Java server still complains about a missing header, _after_ establishing the web socket, then that would be pretty weird, because web sockets themselves handle the 'length' of messages, so there should be no need for such a header.

Trivia:
It starts with the fact that the JSON-RPC spec doesn't actually describe anything about the encoding or transport for sending these messages _at all_. StreamJsonRpc has settled on certain behaviors that fill these gaps, which are in our *handler* classes. You're using `WebSocketMessageHandler`, which makes some assumptions because again, no spec provided the answers to certain questions. One of these assumptions is that we don't need any content length header because web sockets already know the length of a message. 
At the end of the day, if your Java implementation makes conflicting assumptions to StreamJsonRpc's, you can generally rectify that by writing your own handler-derived class to use instead of `WebSocketMessageHandler`. 

But again, I first suspect your web socket handshake is defective, since the error you're seeing suggests that a `GET /` request is in progress, which shouldn't be the case by the time a web socket has been formed.

**Comment by georghinkel** [comment]
Sorry for the interruption. It turned out that I was misunderstanding the conception and the Java server ran JSON-RPC over a plain TCP socket and not a web socket (in the application, there is a proxy in between that converts the web socket to a plain TCP socket). Therefore, the web socket handshake (which is a HTTP GET) with normal HTTP headers but not Content-Length because it just requests a protocol upgrade) was interpreted as a JSON-RPC message where the server requested the Content-Length to be set. Changing the client to a plain TCP socket and the `HeaderDelimitedMessageHandler` made the connection successful. So yes, the root of the problem was that JSON-RPC does not tell anything about transport.
