### ISSUE TITLE
Deserialization of nested objects when using System.Text.Json

### ISSUE THREAD

**Issue by mmoraga** [microsoft/vs-streamjsonrpc#985]
I have an issue with deserialising nested objects when building my project without Newtonsoft.Json. I'm receiving nested objects which I can parse using Newtonsoft by using method such as this:
```
public void foo(JToken token){ }
```

I've tried both using JsonObject as a parameter to the method as well as the individual object itself, but haven't managed to get it working, instead I get this error message:
```
Invocation of "foo" cannot occur because arguments do not match any registered target methods.
```

Simpler methods such as:
```
public void foo(string value)
```
work fine.

**Comment by mmoraga** [comment]
I had to enable `UseSingleObjectParameterDeserialization` to be able to get the parameters as a single `JsonNode`.

**Comment by AArnott** [comment]
When a JSON-RPC request includes an *object* as the value for the `params` property, the spec dictates that each property in the object be interpreted as *named arguments*. It sounds like you want to receive the whole params object as one argument instead. This is a deviation from the spec, which is why it doesn't support this by default. 

But as there are existing applications that deviate from the spec, we have two exceptions to this, both of which you've discovered. Cheers!
